In [ ]:
print("naver", "kakao","sk","samsung", sep=";")

naver;kakao;sk;samsung


삼성전자라는 변수로 50,000원을 바인딩해보세요. 삼성전자 주식 10주를 보유하고 있을 때 총 평가금액을 출력하세요.

In [ ]:
삼성전자 = 50000
총평가금액 = 삼성전자 * 10
print(총평가금액)

500000

012 변수 사용하기
다음 표는 삼성전자의 일부 투자정보입니다. 변수를 사용해서 시가총액, 현재가, PER 등을 바인딩해보세요.


항목	값
시가총액	298조
현재가	50,000원
PER	15.79

In [ ]:
시가총액 = 298000000000000
현재가 = 50000
PER = 15.79

print(시가총액, type(시가총액))
print(현재가, type(현재가)); print(PER, type(PER))

298000000000000 <class 'int'>
50000 <class 'int'>
15.79 <class 'float'>

변수 s와 t에는 각각 문자열이 바인딩 되어있습니다.
 s = "hello"
 t = "python"

In [ ]:
s = "hello"
t = "python"
print(s+"! "+t)

hello! python

>> a = "132"

In [ ]:
a = "132"
print(a, type(a))ㅋ

132 <class 'str'>

num_str = "720"

In [ ]:
num_str = "720"
print(int(num_str), type(int(num_str)))

720 <class 'int'>

year라는 변수가 문자열 타입의 연도를 바인딩하고 있습니다. 이를 정수로 변환한 후 최근 3년의 연도를 화면에 출력해보세요.

In [ ]:
year = "2020"
year = int(year)
# print(year, type(year))

print(year)
print(year-1, year-2, year-3)

2020
2019 2018 2017

에이컨이 월 48,584원에 무이자 36개월의 조건으로 홈쇼핑에서 판매되고 있습니다. 총 금액은 계산한 후 이를 화면에 출력해보세요. (변수사용하기)

In [ ]:
에어컨 = 48584 * 36
print(에어컨)

1749024

021 문자열 인덱싱
letters가 바인딩하는 문자열에서 첫번째와 세번째 문자를 출력하세요.
>> letters = 'python'

In [ ]:
letters = 'python'
print(letters[0], letters[2])

p t

자동차 번호가 다음과 같을 때 뒤에 4자리만 출력하세요.
>> license_plate = "24가 2210"

In [ ]:
license_plate = "24가 2210"
print(license_plate[-4:])

2210

023 문자열 인덱싱
아래의 문자열에서 '홀' 만 출력하세요.

In [ ]:
string = "홀짝홀짝홀짝"
print(string[::2])  # ::오프셋

홀홀홀

24 문자열 슬라이싱
문자열을 거꾸로 뒤집어 출력하세요.

In [ ]:
 string = "PYTHON"
#  print(string[-1], string[-2], string[-3], string[-4])
print(string[::-1])

NOHTYP

025 문자열 치환
아래의 전화번호에서 하이푼 ('-')을 제거하고 출력하세요.

In [ ]:
phone_number = "010-1111-2222"
print(phone_number.split("-"))   # ['010', '1111', '2222']
print(phone_number.replace("-", ''))  # 01011112222

['010', '1111', '2222']
01011112222

url 에 저장된 웹 페이지 주소에서 도메인을 출력하세요.

In [ ]:
url = "http://sharebook.kr"
url_domain = url.split(".")
print(url_domain[-1])

kr

028 문자열은 immutable
아래 코드의 실행 결과를 예상해보세요.

In [ ]:
#  lang = 'python'
#  lang[0] = 'P'
#  print(lang)

# lang 문자열은 할당 메서드를 지원하지 않기 때문에 오류가 발생한다.

029 replace 메서드
아래 문자열에서 소문자 'a'를 대문자 'A'로 변경하세요.

In [ ]:
string = 'abcdfe2a354a32a'
print(string.replace("a", "A"))

Abcdfe2A354A32A

030 replace 메서드
아래 코드의 실행 결과를 예상해보세요.

In [ ]:
string = 'abcd'
string.replace('b', 'B')
print(string)

# replace 값을 담지 않았기 때문에 string 변수값 출력

abcd

033 문자열 곱하기
화면에 '-'를 80개 출력하세요.

In [ ]:
dash = "-"
print(dash * 80)

--------------------------------------------------------------------------------

문자열의 format( ) 메서드를 사용해서 035번 문제를 다시 풀어보세요.

In [ ]:
name1 = "김민수"
age1 = 10
name2 = "이철희"
age2 = 13

print("이름 : {} 나이 : {} ".format(name1, age1))

print(f"이름 : {name1} 나이 : {age1} ")

이름 : 김민수 나이 : 10
이름 : 김민수 나이 : 10

038 컴마 제거하기
삼성전자의 상장주식수가 다음과 같습니다. 컴마를 제거한 후 이를 정수 타입으로 변환해보세요.

In [ ]:
상장주식수 = "5,969,782,550"

count = int(상장주식수.replace(",",""))
print(count, type(count))

5969782550 <class 'int'>

044 endswith 메서드
파일 이름이 문자열로 저장되어 있을 때 **endswith 메서드**를 사용해서 파일 이름이 'xlsx'로 끝나는지 확인해보세요.

In [ ]:
file_name = "보고서.xlsx"
file_name.endswith("xlsx")

# cf. startswith 메서드

True

048 split 메서드
다음과 같이 문자열이 있을 때 btc와 krw로 나눠보세요.

In [ ]:
ticker = "btc_krw"

print(ticker.split("_"))

['btc', 'krw']

050 rstrip 메서드
문자열의 오른쪽에 공백이 있을 때 이를 제거해보세요.

In [ ]:
data = "039490     "
print(data.rstrip())

# 양쪽 공백제거
data1 = "    039490     "
print(data1.strip())

# 왼쪽 공백제거
data2 = "    039490     "
print(data2.lstrip())

039490
039490
039490

051 리스트 생성
2016년 11월 영화 예매 순위 기준 top3는 다음과 같습니다. 영화 제목을 movie_rank 이름의 리스트에 저장해보세요. (순위 정보는 저장하지 않습니다.)

순위	영화


1	닥터 스트레인지


2	스플릿


3	럭키

In [ ]:
movie_rank = ["닥터 스트레인지", "스플릿", "럭키"]

movie_rank = ["추가"]
print(movie_rank)

['추가']

052 리스트에 원소 추가
051의 movie_rank 리스트에 "배트맨"을 추가하라.

In [ ]:
movie_rank = ["닥터 스트레인지", "스플릿", "럭키"]
print(movie_rank)

movie_rank.append("베트맨")
print(movie_rank)

# 원소 사이에 추가하기
movie_rank.insert(1,"슈퍼맨")
print(movie_rank)

# 원소 삭제
del movie_rank[2]
print(movie_rank)

['닥터 스트레인지', '스플릿', '럭키']
['닥터 스트레인지', '스플릿', '럭키', '베트맨']
['닥터 스트레인지', '슈퍼맨', '스플릿', '럭키', '베트맨']
['닥터 스트레인지', '슈퍼맨', '럭키', '베트맨']

057
다음 리스트에서 최댓값과 최솟값을 출력하라. (힌트: min(), max() 함수 사용)

In [ ]:
nums = [1, 2, 3, 4, 5, 6, 7]

print(max(nums))
print(min(nums))

7
1

058
다음 리스트의 합을 출력하라.

In [ ]:
nums = [1, 2, 3, 4, 5]
print(sum(nums))
print(sum(nums) / len(nums))

15
3.0

059
다음 리스트에 저장된 데이터의 개수를 화면에 구하하라.

In [ ]:
cook = ["피자", "김밥", "만두", "양념치킨", "족발", "피자", "김치만두", "쫄면", "소시지", "라면", "팥빙수", "김치전"]
len(cook)

12

063
슬라이싱을 사용해서 짝수만 출력하라.

In [ ]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
nums[1::2]

[2, 4, 6, 8, 10]

066 join 메서드
interest 리스트에는 아래의 데이터가 바인딩되어 있다.

In [ ]:
interest = ['삼성전자', 'LG전자', 'Naver', 'SK하이닉스', '미래에셋대우']
" ".join(interest)

'삼성전자 LG전자 Naver SK하이닉스 미래에셋대우'

071
my_variable 이름의 비어있는 튜플을 만들라.

In [ ]:
my_variable = ();

print(my_variable)

my_variable = (1)
print(my_variable)

()
1

072
2016년 11월 영화 예매 순위 기준 top3는 다음과 같다. 영화 제목을 movie_rank 이름의 튜플에 저장하라. (순위 정보는 저장하지 않는다.)

순위	영화


1	닥터 스트레인지


2	스플릿


3	럭키

In [ ]:
movie_rank = ("닥터스트레인지", "스플릿", "럭키")

073
숫자 1 이 저장된 튜플을 생성하라.

In [ ]:
튜플 = (1)
print(튜플, type(튜플))

1 <class 'int'>

074
다음 코드를 실행해보고 오류가 발생하는 원인을 설명하라.

In [ ]:
t = (1, 2, 3)
# t[0] = 'a' 튜플은 값을 변경할 수 없다.
Traceback (most recent call last):
  File "<pyshell#46>", line 1, in <module>
    t[0] = 'a'
TypeError: 'tuple' object does not support item assignment

SyntaxError: ignored

075
아래와 같이 t에는 1, 2, 3, 4 데이터가 바인딩되어 있다. t가 바인딩하는 데이터 타입은 무엇인가?

In [ ]:
t = 1, 2, 3, 4
print(type(t[0]))

<class 'int'>

076 변수 t에는 아래와 같은 값이 저장되어 있다. 변수 t가 ('A', 'b', 'c') 튜플을 가리키도록 수정 하라.

In [ ]:
t = ('a', 'b', 'c')

# t[0] = 'A'

t = ('A','b','c')

077
다음 튜플을 리스트로 변환하라.

In [ ]:
interest = ('삼성전자', 'LG전자', 'SK Hynix')

data = list(interest)

# print(data)

삼성전자

TypeError: ignored

078
다음 리스트를 튜플로 변경하라.

In [ ]:
interest = ['삼성전자', 'LG전자', 'SK Hynix']

data = tuple(interest)

print(data)

('삼성전자', 'LG전자', 'SK Hynix')

079 튜플 언팩킹
다음 코드의 실행 결과를 예상하라.

In [ ]:
temp = ('apple', 'banana', 'cake')
a, b, c = temp
print(a, b, c)

apple banana cake

080 range 함수
1 부터 99까지의 정수 중 짝수만 저장된 튜플을 생성하라.

In [ ]:
data = tuple(range(2, 100, 2))
print( data )

TypeError: ignored

081 별 표현식
기본적으로 데이터 언패킹은 좌변의 변수와 우변 데이터 개수가 같아야 합니다. 하지만 star expression을 사용하면 변수의 개수가 달라도 데이터 언패킹을 할 수 있습니다. 튜플에 저장된 데이터 중에서 앞에 있는 두 개의 데이터만 필요할 경우 나머지 데이터의 언패킹 코드를 작성할 필요가 없습니다.

다음과 같이 10개의 값이 저장된 scores 리스트가 있을 때, start expression을 사용하여 좌측 8개의 값을 valid_score 변수에 바인딩하여라.

scores = [8.8, 8.9, 8.7, 9.2, 9.3, 9.7, 9.9, 9.5, 7.8, 9.4]

In [ ]:
# 좌측 8개의 값을 valid_score 변수에 바인딩하여라.
scores = [8.8, 8.9, 8.7, 9.2, 9.3, 9.7, 9.9, 9.5, 7.8, 9.4]
*valid_score, s2, s3 = scores
print(valid_score)

# 우측 8개의 값을 valid_score 변수에 바인딩하여라.
s1, s2, *valid_score = scores
print(valid_score)

# start expression을 사용하여 가운데 있는 8개의 값을 valid_score 변수에 바인딩
s1, *valid_score, s3 = scores
print(valid_score)

[8.8, 8.9, 8.7, 9.2, 9.3, 9.7, 9.9, 9.5]
[8.7, 9.2, 9.3, 9.7, 9.9, 9.5, 7.8, 9.4]
[8.9, 8.7, 9.2, 9.3, 9.7, 9.9, 9.5, 7.8]

084 비어있는 딕셔너리
temp 이름의 비어있는 딕셔너리를 만들라.

In [ ]:
temp = {}

085
다음 아이스크림 이름과 희망 가격을 딕셔너리로 구성하라.

이름	희망 가격
메로나	1000
폴라포	1200
빵빠레	1800

In [ ]:
ice = {"메로나" : 1000, "폴라포": 1200, "빵빠레": 1800}
print(ice)

TypeError: ignored